core/urls.py
from core.views import core_views,user_views
from django.conf.urls import url

__author__ = 'andrews'


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url('contact', core_views.contact, name='contact'),
    # url('dashboard', core_views.dashboard, name='dashboard'),
    url('about', core_views.about,  name='about'),
    url('screen', core_views.screen,  name='screen'),
    url('ahenfo', core_views.ahenfo,  name='ahenfo'),
    url('book', core_views.book,  name='book'),


    url('account/login', user_views.sign_in, name='signin'),
    url('account/signup', user_views.sign_up, name='signup'),
    # url('account/logout', user_views.sign_out, name='logout'),
    url('account/register', user_views.registration, name='registration'),
  ]

sarpmedic/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url('', include('core.urls'))
]

core/models/auth_user_demographic.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
sex = (("Male", "MALE"), ("Female", "FEMALE"))
marital = (("Married", "MARRIED"), ("Single", "SINGLE"))
class AuthUserDemographic(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=255,null=True)
    surname = models.CharField(max_length=255,null=True,verbose_name="Surname")
    sex = models.CharField(max_length=255,choices=sex,verbose_name="Gender",default="Male")
    date_of_birth = models.DateField(verbose_name="Date of Birth")
    nationality = models.CharField(max_length=255,null=True)
    religion = models.CharField(max_length=255,null=True)
    marital_status = models.CharField(max_length=255,choices=marital,default="Single")
    address = models.CharField(max_length=255,null=True)
    occupation = models.CharField(max_length=255,null=True)
    email = models.EmailField(null=True)
    mobile = models.CharField(max_length=255,null=True)
    emergency_contact_name = models.CharField(max_length=255,null=True)
    emergency_contact_mobile = models.CharField(max_length=255,null=True)

core/models/biostatistics.py
from django.contrib.auth.models import User
from django.db import models

__author__ = 'andrews'

class Biostatistic(models.Model):
    user = user = models.OneToOneField(User, on_delete=models.CASCADE)
    height = models.DecimalField(max_digits=20,decimal_places=5,null=True)
    weight = models.DecimalField(max_digits=20,decimal_places=5,null=True)
    blood_pressure = models.DecimalField(max_digits=20,decimal_places=5,null=True)

core/models/med_graphic.py
from django.contrib.auth.models import User
from django.db import models

__author__ = 'andrews'

bloodgroup = (("A+","A+"),("A-","A-"),("B+","B+"),("AB+","AB+"),("AB-","AB-"),("O+","O+"),("O-","O-"))
sickling = (("AA","AA"),("AS","AS"),("SS","SS"),("SC","SC"))
g6pd = (("Normal","Normal"),("Partial Defect","Partial Defect"),("Full Defect","Full Defect"))


class Med_graphic(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    blood_group = models.CharField(choices=bloodgroup,max_length=255,null=True)
    sickling_status = models.CharField(choices=sickling,max_length=255,null=True)
    g6pd_status = models.CharField(choices=g6pd,max_length=255,null=True)

core/models/medical_history.py
from django.db import models

__author__ = 'andrews'

class Medical_history(models.Model):
    diabetes_mellitus = models.BooleanField(default=False)
    systematic_hypertension  = models.BooleanField(default=False)
    epilepsy = models.BooleanField(default=False)
    others = models.CharField(max_length=300,null=True)

core/models/signups.py
__author__ = 'andrews'
from django.db import models

class Signup(models.Model):

    first_name = models.CharField(max_length=255,null=True,verbose_name="first_name")
    last_name = models.CharField(max_length=255,null=True,verbose_name="Lastname")
    email = models.EmailField(max_length=255,null=True,verbose_name="Email")
    phone = models.CharField(max_length=255,null=True,verbose_name="Phone")

core/models/social_history.py
from django.db import models

__author__ = 'andrews'

class Social_history(models.Model):
    alcohol = models.BooleanField(default=False)
    smoking  = models.BooleanField(default=False)

core/forms/user_form.py
from core.models.biostatistics import Biostatistic
from core.models.med_graphic import Med_graphic
from core.models.signups import Signup
from django import forms
from django.forms import ModelForm

__author__ = 'andrews'


class LoginForm(forms.Form):
    phone = forms.CharField(label="phone", required=True, max_length=30)
    password = forms.CharField(label="Password", required=True, widget=forms.PasswordInput)
    remember_me = forms.BooleanField(label="Remember me", required=False)


# class RegistrationForm(forms.Form):
#     company_name = forms.CharField(
#         label="Company Name", max_length=255, required=True,
#         error_messages={'required': 'Company name cannot be blank'}
#     )
#     class Meta:
#         model = Biostatistic, Med_graphic
#         exclude = ('company', 'warehouses')
#         widgets = {
#             'street_address': forms.Textarea(attrs={'class': "md-textarea"}),
#             'associated_products': forms.SelectMultiple(attrs={'class': 'mdb-select'}),
#             'registered_location': forms.Select(attrs={'class': 'mdb-select'}),
#             'country': forms.Select(attrs={'class': 'mdb-select'})
#         }


class SignupsForm(ModelForm):

    class Meta:
        model = Signup
        fields = '__all__'

core/views/core_views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    if request.user.is_authenticated:
        # return render(request, ACTIVE_APP+'/dashboard.html')
        #return redirect('create-product')
        pass


    # contact_form = ContactForm()
    # context = {'contact_form': contact_form}

    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about_us.html')


def screen(request):
    return render(request, 'core/screening.html')


def contact(request):
    return render(request, 'core/contact.html')


def ahenfo(request):
   return render(request, 'core/ahenfo.html')



def book(request):
   return render(request, 'core/booking.html')

core/views/user_views.py
from core.forms.user_form import SignupsForm, LoginForm
from core.models.signups import Signup
from django.contrib.auth import authenticate, login
from django.shortcuts import render

__author__ = 'andrews'


def registration(request):

    return render(request, 'core/register.html')

def sign_in(request):
    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            phone = login_form.cleaned_data['phone']
            password = login_form.cleaned_data['password']

            user = authenticate(request, username=phone, password=password)

            if user is not None:
                try:
                    login(request,user)
                except:
                    pass


    login_form = LoginForm()
    context = {'login_form': login_form}

    return render(request, 'core/signin.html',context)

def sign_up(request):
    if request.method == 'POST':
        signup_form = SignupsForm(data=request.POST)
        if signup_form.is_valid():
            first_name = signup_form.cleaned_data['first_name']
            last_name = signup_form.cleaned_data['last_name']
            email = signup_form.cleaned_data['email']
            phone = signup_form.cleaned_data['phone']

            new_signup=Signup(first_name=first_name,last_name=last_name,email=email,phone=phone)
            new_signup.save()

    signup_form = SignupsForm()
    context = {'signup_form': signup_form}
    return render(request, 'core/signup.html',context)

core/templates/base_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Sarpmedic | Home</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->

     <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />


        <link rel="stylesheet" href="{% static 'css/iziToast.min.css' %}" />



</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark primary-color navbar-fixed-top">
    <a class="navbar-brand" href="#"><img src="{% static 'img/overlays/navbar-logo.png' %}"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active active_dec">
                <a class="nav-link" href="{% url 'index' %}"><span class="nav-link-active">Home</span> <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    Screening
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'screen' %}">General</a>
                    <a class="dropdown-item" href="{% url 'screen' %}">Pre-wedding</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ahenfo' %}">Ahenfo Health</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'book' %}">Book On</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'signin' %}">Sign in</a>
                    <a class="dropdown-item" href="{% url 'signup' %}">Sign up</a>
                </div>
            </li>

        </ul>
    </div>
</nav>



 {% block content %}{% endblock %}

<!-- Footer -->
<footer class="page-footer font-small mdb-color pt-4 mt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">

        <!-- Footer links -->
        <div class="row text-center text-md-left mt-3 pb-3">

            <!-- Grid column -->
            <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3 footer_sub-1">
                <h6 class="text-uppercase mb-4 about_us_footer">About Us</h6>
                <p>Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            </div>
            <!-- Grid column -->

            <hr class="w-100 clearfix d-md-none">

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                <h6 class="text-uppercase mb-4 about_us_footer">Products</h6>
                <div class="footer_sub-2">
                    <p><i class="fa fa-chevron-right" aria-hidden="true"></i><a href="#!">Health</a></p>
                    <p><a href="#!"><i class="fa fa-chevron-right" aria-hidden="true"></i>Equipment</a></p>
                    <p><a href="#!"><i class="fa fa-chevron-right" aria-hidden="true"></i>Health</a></p>
                    <p><a href="#!"><i class="fa fa-chevron-right" aria-hidden="true"></i>Equipment</a></p>
                </div>
            </div>
            <!-- Grid column -->

            <hr class="w-100 clearfix d-md-none">

            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                <h6 class="text-uppercase mb-4 about_us_footer">Useful links</h6>
               <div class="footer_sub-2">
                   <p><a href="#!"><i class="fa fa-chevron-right" aria-hidden="true"></i>Your Account</a></p>
                   <p><a href="#!"><i class="fa fa-chevron-right" aria-hidden="true"></i>Monitor</a></p>
                   <p><a href="#!"><i class="fa fa-chevron-right" aria-hidden="true"></i>Your Account</a></p>
                   <p><a href="#!"><i class="fa fa-chevron-right" aria-hidden="true"></i>Your Account</a></p>
               </div>
            </div>

            <!-- Grid column -->
            <hr class="w-100 clearfix d-md-none">

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                <h6 class="text-uppercase mb-4 about_us_footer">Contact</h6>
                <div class="footer_sub-3">
                    <p><i class="fa fa-home mr-3"></i> Kumasi, Ayigya 1233, Ghana</p>
                    <p><i class="fa fa-envelope mr-3"></i> info@sarpmedic.com</p>
                    <p><i class="fa fa-phone mr-3"></i> + 233 24 11 11 111</p>
                    <p><i class="fa fa-print mr-3"></i> + 233 24 11 11 111</p>
                </div>
            </div>
            <!-- Grid column -->

        </div>
        <!-- Footer links -->

        <hr>

        <!-- Grid row -->
        <div class="row d-flex align-items-center">

            <!-- Grid column -->
            <div class="col-md-8 col-lg-8">

                <!--Copyright-->
                <p class="text-center text-md-left">© 2018 Copyright: <a href="#1"><strong> sarpmedic.com</strong></a></p>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-4 ml-lg-0">

                <!-- Social buttons -->
                <div class="text-center text-md-right">
                    <ul class="list-unstyled list-inline">
                        <li class="list-inline-item"><a class="btn-floating btn-sm rgba-white-slight mx-1"><i class="fa fa-facebook"></i></a></li>
                        <li class="list-inline-item"><a class="btn-floating btn-sm rgba-white-slight mx-1"><i class="fa fa-twitter"></i></a></li>
                        <li class="list-inline-item"><a class="btn-floating btn-sm rgba-white-slight mx-1"><i class="fa fa-google-plus"></i></a></li>
                        <li class="list-inline-item"><a class="btn-floating btn-sm rgba-white-slight mx-1"><i class="fa fa-linkedin"></i></a></li>
                        <li class="list-inline-item"><a class="btn-floating btn-sm rgba-white-slight mx-1"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div>

            </div>
            <!-- Grid column -->

        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->

</footer>
<!-- Footer -->
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>


<!-- SCRIPTS -->
    <!-- JQuery -->
    <!-- custom JavaScript -->
    <script type="text/javascript" src="js/main.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

<script  src="{% static 'js/iziToast.min.js' %}" ></script>
<script  src="{% static 'js/mdb.min.js' %}" ></script>
<script  src="{% static 'js/main.js' %}" ></script>
</body>

</html>

core/templates/core/about_us.html
{% extends 'base_home.html' %}

{% block title %}GHUB{% endblock %}

{% block content %}
{% load static %}
<div id="carousel-example-2" class="carousel slide carousel-fade" data-ride="carousel">
    <!--Indicators-->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-2" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-2" data-slide-to="1"></li>
        <li data-target="#carousel-example-2" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <div class="view">
                <img class="d-block w-100 sub_pages_cover" src="{% static 'img/overlays/subpage-cover-1.png' %}" alt="First slide">
                <div class="mask flex-center waves-effect waves-light rgba-teal-strong carousel_background">
                    <div> <!--Section heading-->
                        <h1 class="py-5 font-weight-bold text-center feature_head_1">Features For your health</h1>

                        <p class="px-2 mb-1 pb-3 lead grey-text text-center feature_intro">
                            <i class="fa fa-hand-o-right" aria-hidden="true"></i>About Us
                        </p>
                    </div>
                </div>
            </div>
            <!--<div class="carousel-caption">
                <h3 class="h3-responsive">Light mask</h3>
                <p>First text</p>
            </div>-->
        </div>
        <div class="carousel-item">
            <!--Mask color-->
            <div class="view">
                <img class="d-block w-100 sub_pages_cover" src="{% static 'img/overlays/subpage-cover-1.png' %}" alt="Second slide">
                <div class="mask flex-center waves-effect waves-light rgba-teal-strong carousel_background">
                    <div> <!--Section heading-->
                        <h1 class="py-5 font-weight-bold text-center feature_head_1">Features For your health</h1>

                        <p class="px-2 mb-1 pb-3 lead grey-text text-center feature_intro">
                            <i class="fa fa-hand-o-right" aria-hidden="true"></i>About Us
                        </p>
                    </div>
                </div>
            </div>

        </div>
        <div class="carousel-item">
            <!--Mask color-->
            <div class="view">
                <img class="d-block w-100 sub_pages_cover" src="{% static 'img/overlays/subpage-cover-1.png' %}" alt="Third slide">
                <div class="mask flex-center waves-effect waves-light rgba-teal-strong carousel_background">
                    <div> <!--Section heading-->
                        <h1 class="py-5 font-weight-bold text-center feature_head_1">Features For your health</h1>

                        <p class="px-2 mb-1 pb-3 lead grey-text text-center feature_intro">
                            <i class="fa fa-hand-o-right" aria-hidden="true"></i>About Us
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
</div>
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
                <div class="about_img_div">
                    <img src="{% static 'img/overlays/about_img.png' %}">
                </div>
                <div class="about_main_text">
                    <h1 class="about_text_heading">Our Core Values</h1>
                    <ul class="core_values">
                        <li><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>Here you can use rows and columns here to organize .</li>
                        <li><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>Here you can use rows and columns here to organize .</li>
                        <li><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>Here you can use rows and columns here to organize .</li>
                        <li><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>Here you can use rows and columns here to organize .</li>
                        <li><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>Here you can use rows and columns here to organize .</li>
                        <li><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>Here you can use rows and columns here to organize .</li>
                        <li><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>Here you can use rows and columns here to organize .</li>
                        <li><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>Here you can use rows and columns here to organize .</li>
                        <li><i class="fa fa-chevron-circle-right" aria-hidden="true"></i>Here you can use rows and columns here to organize .</li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8 col-lg-8 col-xl-8 mx-auto mt-3">
                <div class="about_main_text">
                    <h1 class="about_text_heading">What We Do</h1>
                    <p class="about_text__content">
                    efudjfg Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        <br><br>
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        efudjfg Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here yo
                        <br><br>
                        Here you can use rHere you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        efudjfg Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here yo
                        Here you
                        <br><br>
                        Here you can use rHere you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        efudjfg Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here yo
                        Here you
                        <br><br>
                        Here you can use rHere you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        efudjfg Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        Here yo
                        Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    </p>
                </div>
        </div>
        </div>
    </div>
</section>

{% endblock %}

core/templates/core/signin.html
{% extends 'base_home.html' %}

{% block title %}GHUB{% endblock %}

{% block content %}
{% load static %}


    <!-- Start your project here-->

<div class="container">
	<div class="row" style="margin-top:150px;margin-bottom:50px">
       <div class="col-sm-10 offset-sm-1 col-md-6 offset-md-3 col-xs-12">

	     <form action="#" method="post" role="form">
    <section class="form-elegant">

    <!--Form without header-->
    <div class="card">

        <div class="card-body  mycard-color">

            <!--Header-->
            <div class="text-center">
                <h3 class="dark-grey-text mb-5"><strong>Sign In</strong></h3>
            </div>

            <!--Body-->
            <div class="md-form">
			    <i class="fa fa-user prefix"></i>
                {{ login_form.phone }}
                <label for="id_phone">Your Phone Number</label>
            </div>

            <div class="md-form pb-3">
			     <i class="fa fa-lock prefix"></i>
               {{ login_form.password }}
                <label for="id_password">Your Password</label>
            </div>
			<p class="justify-content-end d-flex"><a href="#" class="dark-grey-text font-small ml-1">Forgot Password?</a></p>

            <div class="text-center dark-grey-text mb-3">
                <button type="submit" name="signinbutton" class="btn mybtn-color btn-block btn-rounded  z-depth-1a">Sign in</button>
            </div>


        </div>

        <!--Footer-->
        <div class="modal-footer mx-5 pt-3 mb-1">
            <p class="font-small grey-text d-flex justify-content-end">Not a member? <a href="{% url 'signup' %}" class="blue-text ml-1"> Sign Up</a></p>
        </div>

    </div>
            </section>

	      </form>
           </div>
	   </div>
 	 </div><!--row ends-->


{% endblock %}

core/templates/core/signup.html
{% extends 'base_home.html' %}

{% block title %}GHUB{% endblock %}

{% block content %}
{% load static %}


<div class="container">
	<div class="row" style="margin-top:150px;margin-bottom:50px">

		<div class="card mycard-color col-sm-8 offset-sm-2">

					<form class="form-horizontal" method="post" role="form" action= "{% url 'signup' %}">
                        {% csrf_token %}
					  <div class="text-center" style="margin-top:15px;">
                         <h3 class="dark-grey-text signup-head mb-5">Sign Up</h3>
                      </div>

			<div class="form-row">
		                <div class="col-sm-6">
												<div class="md-form form-group">
												<i class="fa fa-user prefix"></i>

						   							{{ signup_form.first_name }}
                                                    <label for="id_first_name" class="control-label">First Name</label>
												</div>
			            </div>
						<div class="col-sm-6">
												<div class="md-form form-group">
												<i class="fa fa-user prefix"></i>

						   						{{ signup_form.last_name }}
                                                <label for="id_last_name" class="control-label">Last Name</label>
												</div>
						</div>

		    </div>

												<div class="md-form form-group">
												<i class="fa fa-envelope prefix"></i>

						   						{{ signup_form.email }}
                                                <label for="id_email" class="control-label">Email</label>
												</div>

												<div class="md-form form-group">
												<i class="fa fa-phone prefix"></i>

						   						{{ signup_form.phone }}
                                                <label for="id_phone" class="control-label">Phone</label>
						   						</div>

                                       <br><br>
								 <div class="col-sm-8 offset-sm-1 text-center dark-grey-text mb-3" style="margin-top:30px;">
                                   <button type="submit" name="signupbutton" class="btn mybtn-color btn-block btn-rounded  z-depth-1a">Sign Up</button>
                                 </div>
	         <p class="font-small grey-text d-flex justify-content-end">Already have an account? <a href="{% url 'signin' %}" class="blue-text ml-1">Sign In</a></p>

					</form>
</div>

	</div><!--row ends--><br>

</div><!--container ends-->

{% endblock %}